import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  portfolioSidebar: [
    'intro',
    'about-me',
    'experience',
    {
      type: 'category',
      label: 'What I Do',
      items: ['technical-writing', 'docs-as-code', 'technical-stack'],
    },
  ],
  projectsSidebar: [
    {
      type: 'category',
      label: 'Projects',
      link: {
        type: 'generated-index',
        description:
          "A collection of projects I've worked on, with a look at the APIs and documentation behind them.",
      },
      items: [{type: 'autogenerated', dirName: 'projects'}],
    },
  ],
};

export default sidebars;
